### ISSUE TITLE
Mention the current status of the compat layer?

### ISSUE THREAD

**Issue by leofang** [data-apis/scipy-2023-presentation#14]
To me this paragraph ends slightly abruptly:
https://github.com/data-apis/scipy-2023-presentation/blob/acb2ff4a445bc86a356ea5c847a23c004ac2b23a/paper.rst?plain=1#L720-L721
Perhaps we could mention that there are full support for NumPy/CuPy and partial (?) support for PyTorch?

**Comment by kgryte** [comment]
@leofang Does this work for you? https://github.com/data-apis/scipy-2023-presentation/commit/add943e6bb352d68ba542bb3e57c2fd56f9d490a

**Comment by leofang** [comment]
LGTM, thanks, Athan!
