### ISSUE TITLE
Add lockfile for benchmarks

### ISSUE THREAD

**Issue by kgryte** [data-apis/scipy-2023-presentation#24]
We should ensure that we include a lockfile for the benchmarks in this repository in order to ensure reproducibility of results.

**Comment by asmeurer** [comment]
What's the best format to use for this? Note that scikit-learn and scipy were both tested against a specific git commit hash (scipy against an unmerged PR, scikit-learn against an unreleased commit from their `main` branch).

**Comment by kgryte** [comment]
A `requirements.txt` using specific Git hashes? See [SO](https://stackoverflow.com/a/35998253).
