### ISSUE TITLE
Paper authorship

### ISSUE THREAD

**Issue by asmeurer** [data-apis/scipy-2023-presentation#4]
For anyone who wants to be an author on the proceedings paper, you will need to do the following **before Friday, June 2** (note, this was extended from the previous May 26 deadline):

- Review the current draft of the paper https://github.com/data-apis/scipy-2023-presentation/blob/main/paper.rst. You can also download a PDF build of the paper by going to https://github.com/data-apis/scipy-2023-presentation/actions, clicking on the latest build, then clicking `built-paper` under the "Artifacts" section. All authors need to sign off on the contents of the paper.

- Submit a pull request to this repository adding your name as an author to the top of the paper. Feel free to also include any changes to the paper contents in your PR as well. Please be sure to pull first before making changes to avoid merge conflicts.

- You will need to be added as a co-presenter for the talk. This is a requirement of the SciPy proceedings committee: every co-author on the proceedings paper needs to be listed as a co-presenter on the talk. You will not need to actually present the talk with me at the conference, although if you are attending SciPy and are interested in that please let me know.

Note that we are already listing "Data APIs Consortium" as an author on the paper. If you do not wish to complete the above steps, your contributions will be noted via that authorship.

**Comment by szha** [comment]
Thanks for driving this @asmeurer. Glad to see the work finally materialize into a paper and happy to review. Are you looking for feedback at all or just sign-off? What help do you need?

**Comment by rgommers** [comment]
This reads really well, nice work @asmeurer! A few loose ends (TODOs, citations), but those seem straightforward to finish off. I don't have major comments or concerns around the paper structure or contents.

Tip to others: the pdf artifact reads _much_ more pleasantly than the `.rst` version.

**Comment by rgommers** [comment]
> * You will need to be added as a co-presenter for the talk. This is a requirement of the SciPy proceedings committee: every co-author on the proceedings paper needs to be listed as a co-presenter on the talk.

@asmeurer will you send out instructions on how exactly to go about this to those opening PRs for their co-authorship, and can that still be done after May 26 or will it be time-critical?

**Comment by asmeurer** [comment]
> Thanks for driving this @asmeurer. Glad to see the work finally materialize into a paper and happy to review. Are you looking for feedback at all or just sign-off? What help do you need?

Feedback is nice obviously but I only really need a sign-off if you are busy.

**Comment by amueller** [comment]
Thank you for putting this together @asmeurer. This is my sign-off. I'll try to leave comments later, but don't wait on me with anything. And yes, please include my microsoft affiliation :)

**Comment by asmeurer** [comment]
By the way, the proceedings committee has extended the paper submission deadline to Friday, June 2.

**Comment by kgryte** [comment]
Tagging consortium members and other individuals who have been associated with the Consortium (in same way, shape, or form) in this issue for visibility:

@apaszke @edloper @jakirkham @markusweimer @oleksandr-pavlyk @alextp @seberg	@lezcano @teoliphant @alexbaden @aregm @ArvidJB @agarwal-ashish @shwina @curino @devin-petersohn @HyukjinKwon @jreback @jorisvandenbossche @maartenbreddels @mmccarty @ueshin @vnlitvinov @gatorsmile @kkraus14 @datapythonista @dynamicwebpaige @TomAugspurger @ehsantn @hadia206 @ehariri @mroeschke @jbrockmendel @jack-pappas @MarcoGorelli @saulshanabrook @thomasjpfan @tqchen
